[package]
name = "rhai-dylib"
version = "0.1.0"
rust-version = "1.64.0"
edition = "2021"
resolver = "2"
authors = ["Lucas Tabis", "Stephen Chung"]
description = "Native Rust plugins for Rhai"
homepage = "https://rhai.rs"
repository = "https://github.com/rhaiscript"
readme = "README.md"
license = "MIT OR Apache-2.0"
include = ["/src/**/*", "/Cargo.toml", "/README.md", "LICENSE*"]
keywords = [
    "scripting",
    "scripting-engine",
    "scripting-language",
    "embedded",
    "plugins",
]
# categories = []

[dependencies]
libloading = "0.7.3"

# NOTE: Using schungx fork for the RHAI_AHASH_SEED env variable feature.
#       See https://discord.com/channels/767611025456889857/1023946887516131478/1024174374804262963
rhai = { version = "1.10.1", git = "https://github.com/schungx/rhai", features = [
    "internals", # Used to implement the ModuleResolver trait.
] }
